language: erlang
before_install:
 - git clone https://github.com/elixir-lang/elixir
 - cd elixir
 - git checkout v1.0.0
 - cd ..
 - make -C elixir
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script: mix do local.hex --force, test
recipients:
  - joconnor@quarkgames.com
otp_release:
  - 17.3